# Generated by Django 3.1.6 on 2021-02-22 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Deadline',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
