# Generated by Django 3.1.6 on 2021-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0002_auto_20210223_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
