# Generated by Django 3.1.6 on 2021-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0005_auto_20210223_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='PostedDay',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
